logger: 
  path: "./log/" 
  type: "log" 
  name: "logs"
  level: "DEBUG" 
tokens: 
  garant: "a7eacee82a7111f09cbb0050568d72f0" 
bd: 
  host: "89.111.173.169" 
  port: 5432 
  user: "test_user" 
  password: "superpassword" 
  dbname: "test_db"
limited:
  garant: 
    find: 600
    get: 30
