logger: 
  path: "./log/" 
  type: "log" 
  name: "logs"
  level: "DEBUG" 
tokens: 
  garant: "" 
bd: 
  host: "..." 
  port:  
  user: "" 
  password: "" 
  dnname: ""
limited:
  garant: 
    find: 600
    get: 30
